# Generated by Django 4.2.2 on 2025-07-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фото",
                null=True,
                upload_to="users/avatars/",
                verbose_name="Фото",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(
                help_text="Укажите страну", max_length=50, verbose_name="Страна"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Введите адрес электронной почты",
                max_length=254,
                unique=True,
                verbose_name="Email",
            ),
        ),
    ]
