[tool.poetry]
name = "home-work-project-3"
version = "0.1.0"
description = ""
authors = ["Adm <anton.chubshev@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
